7-7-2/DDocker_FE

index.html
src/components/common/Button.tsx
src/components/common/Footer.tsx
src/components/notification/Notice.tsx
src/components/notification/NoticeItem.tsx
src/components/notification/ProfileIcon.tsx
src/constants/notification.ts
src/pages/Layout.tsx
src/pages/Page-Notification.tsx
src/types/types.ts

- 알림 페이지 내 컴포넌트 생성 후 스타일 작업
- 데이터 분기처리 후 조건부 렌더링 필요
closed #18

Feat: NoticeItem

---

public/sprite.svg
src/components/common/MiniProfile.tsx
src/components/follow/EmptyUser.tsx
src/components/follow/UserListItem.tsx
src/components/mypage/MyProfile.tsx
src/components/profile/FollowCount.tsx
src/components/profile/PostsGrid.tsx
src/components/profile/ProfileDetail.tsx
src/components/profile/ProfileImg.tsx
src/pages/Layout.tsx
src/pages/Page-Follow.tsx
src/pages/Page-Profile.tsx
src/styles/layout.ts
src/styles/styles.ts
src/types/types.ts

- 누락된 코드 수정
- 요소 배치 및 스타일 병합
- 팔로우 페이지 조건부 렌더링 추가
closed #26 
- Params 를 이용하여 다른 유저 프로필 페이지로 이동 기능 미구현 (추후 파이어베이스 구현 시 연결)

Feat: Follow Page

---

src/components/home/TodayCaffeineText.tsx
src/components/home/WeeklyPopular.tsx
src/components/home/WeeklyPopularItem.tsx
src/constants/home.ts
src/pages/Page-Home.tsx
src/types/types.ts

- Weekly popular List 기능 구현
- 코드리뷰 반영 수정
#35

Feat: WeeklyPopular Component

---

src/components/posts/PostCard.tsx
src/pages/Page-Posts.tsx

[Screen recording 2023-12-18 5.30.28 PM.webm](https://github.com/7-7-2/DDocker/assets/115582699/145d146e-fd6e-4b6c-b0b3-a8626c691ddc)
- feed 페이지 레이아웃 작업입니다.
close #39

Feat: posts

---

panda.config.ts
src/components/coffee/MyCoffeeSum.tsx
src/components/coffee/SumBoard.tsx
src/components/coffee/SumByType.tsx
src/constants/coffee.ts
src/pages/Page-Coffee.tsx

Feat: caffeine sum board

---

public/sprite.svg
src/atoms/atoms.ts
src/components/common/CaffeineInfo.tsx
src/components/common/CoffeeOptionSelection.tsx
src/components/common/CoffeeSelection.tsx
src/components/home/CaffeineFilter.tsx
src/components/home/CaffeineInfo.tsx
src/components/home/CoffeeMenuSelection.tsx
src/components/home/CoffeeSelection.tsx
src/constants/home.ts
src/styles/styles.ts

- CaffeineFilter,caffeineInfo component
- 셀렉트 시 나타나는 디자인은 추후 데이터 연결하며 수정하도록 하겠습니다!!
- 등록하기 버튼 연결 또한 추후 데이터 연결하며 같이 연결하도록 하겠습니다(데이터 전송 방식 고려)
#37

Feat: CaffeineFilter

---

public/sprite.svg
src/components/common/CoffeeOptionSelection.tsx
src/components/home/CaffeineFilter.tsx
src/components/home/CoffeeMenuSelection.tsx
src/components/post/PostRegister.tsx
src/components/post/RegisterLabel.tsx
src/components/start/SelectFavBrand.tsx
src/constants/common.ts
src/styles/styles.ts

Feat: PostRegister

---

src/pages/Layout.tsx
src/styles/styles.ts

- searchPage + startPage 디자인 상 헤더/푸터 유무에 따른 높이 조절입니다. 
close #50

Fix: startPage height && searchPage height

---

index.html
netlify.toml
src/components/mypage/MyProfile.tsx
src/components/profile/FollowCount.tsx
src/components/profile/PostsGrid.tsx
src/components/profile/ProfileImg.tsx
src/constants/PostsGrid.ts
src/pages/Page-MyPage.tsx

Refactor: Profile Page

---

src/api/user.ts
src/atoms/atoms.ts
src/components/common/Input.tsx
src/components/common/Label.tsx
src/components/start/BrandItem.tsx
src/components/start/CheckNickname.tsx
src/components/start/InitialForm.tsx
src/components/start/SelectFavBrand.tsx
src/components/start/SignIn.tsx
src/constants/common.ts
src/hooks/useInput.tsx
src/styles/styles.ts
src/types/types.ts

- nickname 중복검사 기능 구현
- 회원가입 프로세스 정의
- useInput hook 생성 (discussion에 변경 상세 내용 작성해두겠습니다!)
closed #57 
discussion #22

Feat: nickname check 기능 구현 , useInput hook 생성

---

src/components/common/Footer.tsx
src/components/common/Header.tsx
src/hooks/useShowFooter.tsx
src/pages/Layout.tsx
src/styles/styles.ts

- Feat: useShowfooter clean-up
- Feat: iOS dvh && safe-area inset padding
- Feat: Layout Suspense
- close #62

Fix: Layout

---

package.json
pnpm-lock.yaml
src/api/profile.ts
src/atoms/atoms.ts
src/components/mypage/MyProfile.tsx
src/components/profile/PostsGrid.tsx
src/components/profile/ProfileImg.tsx
src/firebase.config.ts
src/hooks/useFileReader.tsx
src/pages/Page-Profile.tsx

- Profile Img management
---
closed #56

Feat:  Profile Img Regist & Firebase

---

src/api/user.ts
src/atoms/atoms.ts
src/components/common/CoffeeOptionSelection.tsx
src/components/home/CaffeineFilter.tsx
src/components/home/CaffeineInfo.tsx
src/components/home/CoffeeMenuSelection.tsx
src/components/home/CoffeeSelection.tsx
src/components/home/TodayCaffeineText.tsx
src/components/home/TodayMenuItem.tsx
src/components/home/WaterPerCoffee.tsx
src/components/mypage/MyProfile.tsx
src/components/post/PostRegister.tsx
src/components/profile/PostsGrid.tsx
src/components/start/SelectFavBrand.tsx
src/components/start/SignIn.tsx
src/datas/coffees.ts
src/hooks/useGetCacheData.tsx
src/hooks/useSetCacheData.tsx
src/hooks/useSetUserInitialInfo.ts
src/pages/Page-Start.tsx
src/types/types.ts

- PWA cache storage 로직 추가
- caffeine filter 기능 구현
- post regist data 저장 로직
#59

Feat: PWA cache storage 로직 추가, caffeine filter 기능 구현

---

src/api/user.ts
src/atoms/atoms.ts
src/components/home/CoffeeMenuSelection.tsx
src/components/home/TodayCaffeineInfo.tsx
src/components/home/TodayCaffeineText.tsx
src/components/home/WaterPerCoffee.tsx
src/components/mypage/MyProfile.tsx
src/components/start/SignIn.tsx
src/pages/Page-Start.tsx
src/types/types.ts

- ocal storage > cache storage로 로직 변경 
- caffeine filter 오류 수정
closed #73

Fix: local storage > cache storage로 로직 변경 및 caffeine filter 오류 수정

---

index.html
src/components/common/Header.tsx
src/components/post/PostRegister.tsx

[Screen recording 2023-12-24 4.38.32 PM.webm](https://github.com/7-7-2/DDocker/assets/115582699/873739cd-55e1-4838-8125-e4cd375342ad)
- 등록 페이지 이미지 선택입니다. 프레임 비율 고정되어 있습니다.
- 첫 페이지 진입시 깜빡임 현상 개선을 위해서 font preload도 적용되어 있습니다. 
- close #76  #77

Feat: Register Img Editor

---

package.json
pnpm-lock.yaml
src/api/axiosInterceptor.ts
src/api/post.ts
src/api/profile.ts
src/api/user.ts
src/atoms/atoms.ts
src/components/home/CoffeeIntake.tsx
src/components/home/CoffeeMenuSelection.tsx
src/components/home/TodayCaffeineInfo.tsx
src/components/home/TodayCaffeineText.tsx
src/components/home/WaterPerCoffee.tsx
src/components/post/PostRegister.tsx
src/components/start/BrandItem.tsx
src/components/start/CheckNickname.tsx
src/components/start/InitialForm.tsx
src/components/start/SelectFavBrand.tsx
src/components/start/SelectGender.tsx
src/components/start/SignIn.tsx
src/hooks/useGetProfileImg.tsx
src/hooks/useSetCacheData.tsx
src/hooks/useSetUserInitialInfo.ts
src/pages/Page-Start.tsx
src/types/types.ts

- social auth, checkNickname, getUserInfo api 연결 추후 수정 예정
- post.api file firebase > server api 변경
- error 임시 수정
- closed #90 
- closed #92

Refactor: social auth, checkNickname, getUserInfo api 

---

src/components/common/Icon.tsx
src/components/post/PostDetail.tsx
src/components/post/PostSocial.tsx
src/components/post/PostSocialCount.tsx
src/components/posts/PostCard.tsx
src/pages/Page-Posts.tsx
src/types/types.ts

Feat: toggleLike

---

src/api/post.ts
src/atoms/atoms.ts
src/components/common/CoffeeOptionSelection.tsx
src/components/home/CaffeineInfo.tsx
src/components/home/CoffeeMenuSelection.tsx
src/components/home/CoffeeSelection.tsx
src/components/home/TodayCaffeineText.tsx
src/components/home/WaterPerCoffee.tsx
src/components/home/WeeklyPopular.tsx
src/components/home/WeeklyPopularItem.tsx
src/components/post/PostRegister.tsx
src/components/start/BrandItem.tsx
src/components/start/SelectFavBrand.tsx
src/types/types.ts
src/utils/setBrandList.ts

- weeklyPopular api, Brand api 연결 및 registPostState 수정
- #93

Refactor: WeeklyPopular api, Brand api 

---

package.json
pnpm-lock.yaml
src/api/post.ts
src/components/post/PostSocial.tsx
src/hooks/useInfiniteScroll.tsx
src/hooks/useIntersection.tsx
src/hooks/useTargetInfiniteScroll.tsx
src/pages/Page-Posts.tsx
src/types/types.ts

Feat: posts page Infinite Scroll

---

src/api/post.ts
src/hooks/useInfiniteScroll.tsx

Fix: getFollowingPosts route && Infinite Scroll enabled

---

package.json
pnpm-lock.yaml
src/api/axiosInterceptor.ts
src/api/post.ts
src/api/user.ts
src/atoms/atoms.ts
src/components/common/CoffeeOptionSelection.tsx
src/components/home/CaffeineInfo.tsx
src/components/home/ChartItem.tsx
src/components/home/CoffeeIntake.tsx
src/components/home/CoffeeMenuSelection.tsx
src/components/home/CoffeeSelection.tsx
src/components/home/TodayCaffeineText.tsx
src/components/home/TodayMenuItem.tsx
src/components/home/WaterIntake.tsx
src/components/home/WaterPerCoffee.tsx
src/components/post/PostRegister.tsx
src/components/start/CheckNickname.tsx
src/components/start/SelectFavBrand.tsx
src/components/start/SignIn.tsx
src/constants/home.ts
src/hooks/useGetCoffeeList.ts
src/hooks/useGetTodayCoffeeData.ts
src/hooks/useGetUserInfo.ts
src/hooks/useResetSelectedCoffee.ts
src/hooks/useSetCacheData.tsx
src/pages/Page-Home.tsx
src/types/types.ts

- React Circular Progressbar 적용
- Home-page Refactoring
- #103

 Feat: page-home Progressbar, Refactoring

---

src/api/post.ts
src/api/user.ts
src/atoms/atoms.ts
src/components/common/FooterIcon.tsx
src/components/home/CoffeeIntake.tsx
src/components/home/CoffeeMenuSelection.tsx
src/components/home/TodayMenuItem.tsx
src/components/home/WaterPerCoffee.tsx
src/components/post/PostRegister.tsx
src/components/profile/FollowCount.tsx
src/components/profile/PostsGrid.tsx
src/components/profile/ProfileDetail.tsx
src/hooks/useGetCoffeeList.ts
src/hooks/useGetTodayCoffeeData.ts
src/hooks/useGetUserInfo.ts
src/hooks/useInfiniteScroll.tsx
src/hooks/useTargetInfiniteScroll.tsx
src/pages/Page-Profile.tsx
src/types/types.ts
src/utils/setBrandList.ts

- ProFile-Page api 연결 및 구조 refactoring
- #107

Feat: profile-page api && refactoring

---

src/api/coffee.ts
src/components/coffee/MyCoffeeSum.tsx
src/components/coffee/SumBoard.tsx
src/components/coffee/SumByType.tsx
src/constants/coffee.ts
src/pages/Page-Coffee.tsx
src/styles/styles.ts

Feat: Public && Private Coffee SumBoard

---

src/components/post/PostDetail.tsx
src/components/post/PostInput.tsx
src/components/post/PostSocial.tsx
src/components/post/overlay/BackgroundLayer.tsx
src/components/post/overlay/PostOptions.tsx
src/components/post/overlay/PublicOption.tsx
src/components/posts/PostCard.tsx
src/hooks/usePostOptions.tsx
src/hooks/useVerifyOwner.tsx

Feat: enhance permission of PostDetail features && posts option

---

.eslintrc.cjs
package.json
pnpm-lock.yaml
src/components/post/PostDetail.tsx
src/components/post/PostInput.tsx
src/components/post/PostSocial.tsx
src/components/post/overlay/BackgroundLayer.tsx
src/components/post/overlay/PostOptions.tsx
src/components/post/overlay/PublicOption.tsx
src/components/posts/PostCard.tsx
src/hooks/google/useTrackRoute.tsx
src/hooks/usePostOptions.tsx
src/hooks/useVerifyOwner.tsx
src/main.tsx
src/pages/Layout.tsx

Feat: google analytics

---

src/api/post.ts
src/atoms/atoms.ts
src/components/common/Label.tsx
src/components/post/PostInputTitle.tsx
src/components/post/PostRegister.tsx
src/components/start/CheckNickname.tsx
src/components/start/InitialForm.tsx
src/components/start/SelectGender.tsx
src/constants/common.ts
src/hooks/useGetUserInfo.ts
src/hooks/useInput.tsx
src/hooks/useValidateNickname.ts
src/pages/Page-Home.tsx
src/types/types.ts
src/utils/validateNickname.ts

- Input && useInput 변경사항 적용
- 닉네임 유효성 검사
#111

Refactor: Input component 변경 적용

---

src/api/search.ts
src/atoms/atoms.ts
src/components/search/HistoryHeader.tsx
src/components/search/HistoryList.tsx
src/components/search/SearchBar.tsx
src/components/search/SearchHistory.tsx
src/components/search/SearchListItem.tsx
src/hooks/useDebounce.tsx
src/hooks/useSearchInput.tsx
src/hooks/useSetCacheData.tsx
src/hooks/useSetHistory.tsx
src/pages/Layout.tsx
src/pages/Page-Search.tsx
src/styles/styles.ts
src/types/types.ts

Feat: debounced search

---

public/sprite.svg
src/api/post.ts
src/components/common/AlertBubble.tsx
src/components/common/CoffeeOptionSelection.tsx
src/components/common/FooterIcon.tsx
src/components/common/SelectBox.tsx
src/components/common/SelectBtn.tsx
src/components/common/SelectOption.tsx
src/components/home/CaffeineFilter.tsx
src/components/home/CoffeeMenuSelection.tsx
src/components/home/TodayCaffeineText.tsx
src/components/home/WaterIntake.tsx
src/components/home/WeeklyPopular.tsx
src/hooks/useGetCachedWater.ts
src/hooks/useGetCoffeeList.ts
src/hooks/useGetPopularList.ts
src/hooks/useGetTodayCoffeeData.ts
src/hooks/useGetUserInfo.ts
src/hooks/useSelect.ts
src/hooks/useSetCacheData.tsx
src/pages/Page-Start.tsx

- Home-page 
- !userInfo && null TypeError
- weeklyPopular data fetching && !auth
- waterPerCoffee data cacheing
- coffeeOptions Max Shot Setting
- Home page design
-  Common
- AlretBubble
- SelectBox && SelectBtn && SelectOption
- #126

Fix: Home-page, Common

---

panda.config.ts
src/api/trend.ts
src/components/common/CTA.tsx
src/components/common/MiniProfile.tsx
src/components/home/CoffeeIntake.tsx
src/components/home/WaterPerCoffee.tsx
src/components/notification/Notice.tsx
src/components/post/CheckReply.tsx
src/components/post/PostComments.tsx
src/components/post/PostedAt.tsx
src/components/posts/trend/DailyTrendCard.tsx
src/components/posts/trend/DailyTrendSlider.tsx
src/components/posts/trend/PostDiscoveryCTA.tsx
src/components/posts/trend/PostsBrandPopular.tsx
src/components/posts/trend/PostsSortBy.tsx
src/components/posts/trend/PostsTrend.tsx
src/components/posts/trend/TrendBubbleText.tsx
src/components/posts/trend/carousel/BrandCard.tsx
src/components/posts/trend/carousel/BrandCarousel.tsx
src/components/posts/trend/carousel/BrandPage.tsx
src/components/posts/trend/carousel/Bullet.tsx
src/components/profile/ProfileDetail.tsx
src/constants/texts.ts
src/styles/styles.ts
src/types/types.ts
src/utils/convertBrandName.ts

- CTA(공통 컴포넌트) 사용시 상단 안내 텍스트(text), 하단 버튼 내부 텍스트(actionText), 버튼 기능(fn) props으로 전달 후 사용하시면 됩니다.
close #130

Feat: PostBrandPopular with sortBy

---

public/sprite.svg
src/components/post/PostSocial.tsx
src/components/posts/trend/DailyTrendCard.tsx
src/components/posts/trend/DailyTrendImage.tsx
src/components/posts/trend/FloatingBtn.tsx
src/components/posts/trend/PostsTrend.tsx
src/hooks/useLikeOnPost.tsx
src/types/types.ts
src/utils/getBrandPath.ts

Feat: Floating Button to brand carousel

---

src/api/follow.ts
src/api/likes.ts
src/components/common/Button.tsx
src/components/common/CTA.tsx
src/components/post/PostComments.tsx
src/components/post/PostDetail.tsx
src/components/post/PostInput.tsx
src/components/post/overlay/ConfirmButtons.tsx
src/components/post/overlay/ConfirmDelete.tsx
src/components/post/overlay/Option.tsx
src/components/post/overlay/PostOwnerOption.tsx
src/components/posts/following/PostCard.tsx
src/constants/texts.ts
src/hooks/usePostOptions.tsx
src/styles/styles.ts
src/types/types.ts

Fix: post detail

---

src/components/posts/following/FollowDiscoveryCTA.tsx
src/components/posts/following/PostsFollowing.tsx
src/components/posts/following/SignInCTA.tsx
src/constants/texts.ts
src/styles/styles.ts

Feat: private posts following

---

src/components/coffee/MyCoffeeSum.tsx
src/components/common/CTA.tsx
src/components/home/CaffeineFilter.tsx
src/components/post/PostInput.tsx
src/components/posts/trend/PostDiscoveryCTA.tsx
src/hooks/post/useLikeOnPost.ts
src/hooks/useGetSignedIn.ts
src/hooks/useGetTodayCoffeeData.ts
src/hooks/useTargetInfiniteScroll.ts
src/pages/Page-Coffee.tsx
src/pages/Page-Search.tsx

Refactor: signedIn

---

src/components/posts/trend/PostsBrandPopular.tsx
src/components/posts/trend/carousel/BrandCard.tsx
src/components/posts/trend/carousel/BrandCarousel.tsx
src/constants/texts.ts
src/hooks/post/useSelectCard.ts
src/hooks/post/useSetInitialBrand.ts
src/hooks/post/useVerifyOwner.ts

Feat: focus to favorite brand

---

src/constants/profile.ts
src/hooks/useInfiniteScroll.ts
src/hooks/useTargetInfiniteScroll.ts
src/pages/Page-Follow.tsx
src/pages/Page-Profile.tsx

Fix: follow page API call on guest mode

---

src/api/coffee.ts
src/atoms/atoms.ts
src/components/coffee/MyCalendar.tsx
src/components/coffee/MyCoffeeSum.tsx
src/components/mypage/MyProfile.tsx
src/hooks/coffee/useGetMyCoffeeSum.ts
src/pages/Page-Home.tsx

- MyCoffeeSum && activeMonth
- getCalendarData && maxDate, minDate
- closed #164

Feat: MyCoffeeSum && activeMonth

---

panda.config.ts
src/api/post.ts
src/components/common/ImgCropper.tsx
src/components/common/ImgRegister.tsx
src/components/mypage/EditProfileImg.tsx
src/components/mypage/MyProfile.tsx
src/components/post/PostDetail.tsx
src/components/post/PostRegister.tsx
src/components/post/PostSocial.tsx
src/components/post/PostSocialCount.tsx
src/components/posts/following/PostBody.tsx
src/components/posts/trend/DailyTrendImage.tsx
src/components/profile/ProfileDetail.tsx
src/components/start/InitialForm.tsx
src/hooks/post/useRefIntoView.ts
src/hooks/useCloudStorage.ts
src/hooks/useCompressImage.ts
src/styles/styles.ts
src/types/types.ts

- webshare API 공유, fallback clipboard copy처리 
- png => webp 파일 형식 통일 
- image-compression시 압축시간 소요에 따른 loading indicator 추가
- close #137 
- close #178 
- close #180

Feat: share post

---

src/components/post/PostDetail.tsx
src/components/post/overlay/ConfirmDelete.tsx
src/components/posts/following/PostCard.tsx
src/hooks/useNavigateTo.ts

- 기존 팔로잉 유저목록에서만 사용하던 <PostCard /> 트렌드에서도 사용으로 권한(게시글 소유자) 검증 추가
- close #187

Feat: handle options on postcard

---

src/api/post.ts
src/components/home/CoffeeSelection.tsx
src/components/home/TodayCaffeineText.tsx
src/components/home/WaterPerCoffee.tsx
src/components/post/PostInputTitle.tsx
src/components/post/PostRegister.tsx
src/components/post/overlay/PostOwnerOption.tsx
src/constants/common.ts
src/hooks/home/useGetTodayCoffeeData.ts
src/hooks/post/useImageCropper.ts
src/hooks/post/useUpadatePost.ts
src/hooks/useComposeHeader.ts
src/hooks/useDeleteCacheData.ts
src/hooks/useInput.ts
src/hooks/useResetSelectedCoffee.ts
src/hooks/useSetCacheData.ts
src/pages/Page-Home.tsx
src/pages/Page-Post.tsx
src/pages/Router.tsx
src/types/types.ts

Feat: update post

---

src/components/home/HomeFooter.tsx
src/components/home/WaterIntake.tsx
src/hooks/home/useGetCachedWater.ts
src/hooks/home/useGetPopularList.ts
src/hooks/home/useGetTodayCoffeeData.ts
src/pages/Page-Home.tsx
src/pages/Page-Post.tsx

- waterIntake cachedData 수정
- 'water/${userId}'
- WeeklyPopular && getWeeklyPopularList
- 자정에 데이터 refetch
- 
- closed #184

Feat: WaterIntake && cachedData , WeeklyPopular && getWeeklyPopularList

---

src/api/user.ts
src/components/common/ModalCTA.tsx
src/components/mypage/MyProfile.tsx
src/components/post/overlay/ConfirmDeleteUser.tsx
src/components/profile/AnonymousUserCard.tsx
src/constants/profile.ts
src/constants/texts.ts
src/hooks/MyPage/useHandleAuth.ts
src/utils/validateNickname.ts

- 로그아웃 기능 구현
- 회원탈퇴 기능 구현 및 탈퇴 확인 모달
-  회원탈퇴 api 연결
- myPage 버튼 추가
- 탈퇴 확인 모달 추가
- closed #192

Feat: signOut && deleteAccount

---

src/components/common/FooterIcon.tsx

-  푸터 외 페이지(알림, 게시글)등에서 푸터 영역 해당 페이지들로 이동시 아이콘 불일치 수정
- close #176

Fix: footer icon match on page navigation

---

src/components/profile/EmptyPostGrid.tsx
src/hooks/post/usePostOptions.ts
src/hooks/useGetUserInfo.ts

- myPage 게시글 없을 시 CTA클릭 함수 내 footer상태 업데이트
- page-Profile && guest mode && userInfo ( ! data fetching)
- closed #206 
- closed #198

Fix : profile page

---

src/api/r2.ts
src/components/mypage/MyProfile.tsx
src/components/post/overlay/ConfirmDeleteUser.tsx
src/components/profile/EmptyPostGrid.tsx
src/constants/common.ts
src/hooks/MyPage/useHandleAuth.ts
src/hooks/useCloudStorage.ts

- deleteAccount => deleteStorage(profile, posts)
- confirmDeleteUser constants
- handleClickBtn && unedited profile image  =>  remain profile image
- EmptyPostGrid container size
- closed #204 
- closed #205 
- closed #212

Fix: deleteAccount (deleteStorage), edit profile

---

panda.config.ts
public/sprite.svg
src/api/report.ts
src/atoms/atoms.ts
src/components/home/HomeFooter.tsx
src/components/post/Comment.tsx
src/components/post/CommentAction.tsx
src/components/post/CommentProto.tsx
src/components/post/PostComments.tsx
src/components/post/PostInput.tsx
src/components/post/Replies.tsx
src/components/posts/following/PostBody.tsx
src/constants/home.ts
src/constants/texts.ts
src/hooks/post/useDetectSlide.ts
src/hooks/post/useSelectCard.ts
src/pages/Page-Notification.tsx
src/pages/Page-Report.tsx
src/styles/styles.ts
src/types/types.ts

- 댓글/답글 신고 API적용 및 단독 선택 상태 추가
- 알림 페이지 알림 없을시 메시지 추가
- 푸터 하단 이미지 저작권 문구 추가
- 캐러셀 포커싱 수정  
- close #200 
- close #209 
- close #210 
- close #211

Feat: delete or report on comment and reply with swipe

---

.github/workflows/deploy.yaml

Feat: set up CI/CD

---

src/components/coffee/MyCalendar.tsx
src/components/coffee/MyCoffeeSum.tsx
src/components/coffee/SumBoard.tsx
src/components/common/FooterIcon.tsx
src/components/common/SelectBox.tsx
src/components/common/SelectBtn.tsx
src/components/home/WaterIntake.tsx
src/components/post/PostDetail.tsx
src/components/post/PostRegister.tsx
src/components/profile/FollowCount.tsx
src/components/start/InitialForm.tsx
src/components/start/SelectFavBrand.tsx
src/constants/profile.ts
src/hooks/coffee/useGetCalendarData.ts
src/hooks/coffee/useGetMyCoffeeSum.ts
src/hooks/post/useResetRegistInfo.ts
src/hooks/useGetUserInfo.ts
src/pages/Layout.tsx
src/pages/Page-Profile.tsx
src/styles/styles.ts

- coffeeMenuSelection.tsx > selectBox 
- 브랜드 선택 전, 메뉴 선택 박스 disabled
- 초기화 버튼 클릭 후에도 FavBrand 선택 유지 
- WaterIntake.tsx
- FollowCount > 팔로워 팔로잉 순서 변경
- 비회원 유저 마이페이지 방문시 로그인 유도 화면 > 페이지 재진입시 useInfiniteScroll Error 발생
- 게시글 등록시 이미지 없이도 업로드, 필수로 전환
- 이미지, 카페인 정보 필수 지정
- post  수정페이지 집입 후 미수정 상태로 수정페이지를 벗어났을때 > registPostState reset
- 수정페이지 레이아웃 
- 회원가입시 브랜드 추가 => brand data 추가시 자동 생성
- 회원가입시 aboutMe 기본값 수정
- MyCoffeeSum 디자인 수정
- useGetCalendarData && react-query 적용
- closed #220 
- closed #230 
- closed #223 
- closed #216 
- closed #232

Fix: various fixes

---

src/components/common/Input.tsx
src/components/post/PostInput.tsx
src/types/types.ts

- 모바일 댓글작성시 enter키를 통한 댓글/답글 작성 처리 추가
- close #240

Feat: handleSubmitCommentByEnter

---

src/api/user.ts
src/components/mypage/MyProfile.tsx
src/components/start/SelectFavBrand.tsx
src/constants/profile.ts
src/hooks/MyPage/useHandleAuth.ts

- deleteAccount Flow
- closed #236

Fix: deleteAccount Flow

---

src/components/home/TodayCaffeineText.tsx
src/components/home/TodayMenuItem.tsx
src/components/home/WaterIntake.tsx
src/components/home/WeeklyPopularItem.tsx
src/components/mypage/EditProfileImg.tsx
src/components/posts/PostImg.tsx
src/components/posts/following/PostBody.tsx
src/components/start/BrandItem.tsx

- 크기없는 기존 이미지 크기 설정을 통한 렌더링 최적화
- ref) #181  
- close #182

Feat: optimize img size

---

src/components/post/PostDetail.tsx
src/components/posts/following/PostBody.tsx
src/components/posts/following/PostCard.tsx
src/components/profile/MemberProfile.tsx
src/components/profile/PostsGrid.tsx
src/constants/SEOData.ts
src/hooks/notification/useFetchSSE.ts

- heartbeat(ping)적용, 알림페이지 클라이언트-서버 커넥션 유지
- 컴포넌트 렌더링 위치 조정
- PostDetail: useQuery => useQueries 변경
- close #247

Feat: set heartbeat connection with server

---

package.json
pnpm-lock.yaml
src/components/common/SEOMeta.tsx
src/components/support/NoticeDetail.tsx
src/constants/SEOData.ts
src/pages/Page-Follow.tsx
src/pages/Page-Post.tsx
src/pages/Page-Profile.tsx
src/pages/Page-Report.tsx
vite.config.ts

- Apply Puppeteer and Prerenderer for prerendering
- fix metaData 
- closed #246

Feat: Apply Puppeteer and Prerenderer for prerendering , fix metaData 

---

public/pwabuilder-sw.js
src/components/common/SEOMeta.tsx

- theme-color meta 설정
- close #251

Feat: set meta theme color

---

public/pwabuilder-sw.js
src/components/common/SEOMeta.tsx

Feat: integrate dev to main

---

.gitignore
.puppeteerrc.cjs
package.json

- puppeteer 스크립트 오류 해결
- close #254

Hotfix: upadte puppeteer script

---

.gitignore
.puppeteerrc.cjs
package.json
public/pwabuilder-sw.js

Hotfix: update service worker caching

---

public/pwabuilder-sw.js
src/components/coffee/ScrollInducer.tsx
src/pages/Page-Error.tsx

- dynamic caching 조건 수정
- 에러 페이지 스타일 수정
- close #264

Fix: dynamic caching

---

public/manifest.json
src/api/post.ts
src/components/coffee/LogInCTA.tsx
src/components/home/WeeklyPopular.tsx
src/hooks/useGetCoffeeList.ts
src/pages/Page-Error.tsx
src/types/types.ts

- ios layout (page-errorr, LoginCTA)
- WeeklyPopularTypes 수정
- closed #267

Fix: ios layout (page-errorr, LoginCTA), WeeklyPopularTypes

---

src/components/home/WeeklyPopular.tsx
src/components/home/WeeklyPopularItem.tsx

- WeeklyPopualarItem apply lazy
- closed #270

Fix: WeeklyPopualarItem

---

.github/workflows/deploy.yaml
src/components/post/Comment.tsx
src/components/post/CommentAction.tsx
src/components/post/CommentProto.tsx
src/components/post/PostComments.tsx
src/components/post/Reply.tsx
src/types/types.ts

- post 진입시 lazy 미적용으로 인해 DOM tree에 Comment생성시 null값 전달 오류로 인한 렌더링 오류
- Comment, CommentProto 타입 수정(컴포넌트명과 중복)
- AWS sync size비교 옵션 추가
- close #273

Fix: lazy load postDetail

---

src/components/home/WeeklyPopularItem.tsx
src/components/post/PostComments.tsx
src/components/support/FAQ.tsx
src/constants/home.ts
src/constants/support.ts

- add FAQ non-member text
- weeklyPopularList design
- closed #272

Fix: add FAQ non-member text, weeklyPopularList designFix/272 common

---

src/components/common/HeaderCloseIcon.tsx
src/components/common/SelectBox.tsx
src/components/home/WaterPerCoffee.tsx
src/components/home/WeeklyPopular.tsx
src/components/post/PostComments.tsx
src/components/post/PostRegister.tsx
src/components/posts/trend/DailyTrendImage.tsx
src/hooks/useNavigateTo.ts
src/pages/Layout.tsx
src/utils/getBrandPath.ts

- 전반적인 스타일 수정
- getBrandPath 오타 수정
- weeklyPopularList item 조건문 추가
- closed #276

Fix: for beta service (design, error)

---

public/pwabuilder-sw.js
src/components/post/PostComments.tsx

- SSE요청 Service Worker event listener 제외 조건 추가
- 댓글 렌더링 조건 수정
- close #278

Fix: exclude SSE connection being intercepted by SW

---

src/components/post/CommentProto.tsx
src/hooks/home/useGetPopularList.ts

- 비회원 포스트 댓글 1개 이상 있는 경우 error 수정
- 인기브랜드 error 수정
- closed #283

Fix: non-member && post comment > 0 && postDetail erro

---

src/components/follow/UserListItem.tsx
src/components/home/WeeklyPopular.tsx
src/components/mypage/MyProfile.tsx
src/components/post/CommentProto.tsx
src/components/post/PostDetail.tsx
src/components/posts/following/PostBody.tsx
src/components/posts/following/PostCard.tsx
src/components/posts/following/PostsFollowing.tsx
src/components/profile/EmptyPostGrid.tsx
src/components/profile/FollowCount.tsx
src/components/profile/MemberProfile.tsx
src/components/profile/PostsGrid.tsx
src/components/search/SearchListItem.tsx
src/components/support/CustomerCenter.tsx
src/components/support/FAQ.tsx
src/hooks/profile/useGetCheckFollowing.ts
src/pages/Page-Coffee.tsx
src/pages/Page-Notification.tsx
src/pages/Page-Post.tsx
src/pages/Page-Posts.tsx
src/pages/Page-Profile.tsx
src/pages/Page-Start.tsx
src/pages/Page-Support.tsx
src/types/types.ts
src/utils/timestampToDate.ts

- lazy loaded components suspense로 wrapping
- 타임존 함수 수정(KST로 비교)
- close #287

Refactor: lazy with Suspense wrapping

---

package.json
pnpm-lock.yaml
src/components/common/CTA.tsx
src/components/home/TodayCaffeineText.tsx
src/pages/Page-Search.tsx
vite.config.ts

- vite build gzip적용
- close #292 close #294

Refactor: gzip

---

pnpm-lock.yaml
src/components/start/SignIn.tsx

- dependency  누락 pnpm-lock.yaml 설치 후 수정
-

Fix: dependency

---

src/components/start/SignIn.tsx
src/hooks/useGetUserInfo.ts
src/pages/Page-Start.tsx

- startPage nav error
- closed #299

Fix: signIn nav error

---

public/pwabuilder-sw.js

- start페이지 서비스워커 동적 캐싱 제외
- close #302

Fix: exclude signin/signup process from service worker caching

---

public/pwabuilder-sw.js

- SignIn 컴포넌트 캐싱 제외
- close #305

Fix: signin component

---

public/pwabuilder-sw.js
src/components/home/WaterPerCoffee.tsx

- Fix: WaterPerCoffee & pwabuilder
- closed #309

Fix: WaterPerCoffee & pwabuilder

---

public/pwabuilder-sw.js
src/api/r2.ts
src/components/post/PostRegister.tsx
src/hooks/home/useGetPopularList.ts
src/hooks/useSetCacheData.ts
src/main.css
src/types/types.ts

- fix WeeklyPopularList data fetching
- refactoring PostRegister logic
- fix getPresignedUploadUrl response
- set default font size
- closed #324

Fix: Presigned Upload Url response, Weekly Popular List data fetching
